### ISSUE TITLE
return a meaningful errror message when oauth_consumer_key is missing

### ISSUE THREAD

**Issue by pdpinch** [mitodl/sga-lti#38]
This is an edge case, so we should discuss before implementing. 

Steps to reproduce:

1. Add lti-consumer xblock to the course via advanced settings, but leave lti passports blank
2. Add SGA-LTI as you normally would

Expected outcome:

an error message indicating that the consumer key is bad and / or missing.

Actual outcome:

I'm redirected to the studio error message, which is particularly confusing if the user isn't actually in studio:

<img src="https://box.everhelper.me/attachment/512692/09a2683f-ab31-44a6-8134-09fd67836b69/623857-KsesSqSoTUkNlM4b/screen.png">

**Comment by alvinsiu** [comment]
This was an issue if you were already logged in and then went to another instance of the tool with bad LTI credentials.  We've updated the django-auth-lti library to pass bad authentication information through to the middleware.  It now also says "Bad or missing LTI credentials" if this occurs.
