### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by sfrucht** [mitodl/sga-lti#49]
A user cannot be enrolled in multiple courses with the LTI. A 500 error appears.

**Comment by alvinsiu** [comment]
Do you have server error logs we can look at, or can we have access to another course?  We can't replicate this issue otherwise.

**Comment by sfrucht** [comment]
I added you to the following course:
https://studio.edge.edx.org/course/course-v1:MITx+SGA101+2T2016

You are an Admin and can add others if necessary.

**Comment by alvinsiu** [comment]
Thanks for adding me.  I can't seem to replicate this bug - what steps did you take to get this error?

**Comment by blarghmatey** [comment]
I showed @alvinsiu how to access the logs on Heroku so that he can view the error logs as they are being generated.

**Comment by sfrucht** [comment]
Thanks @blarghmatey 

@alvinsiu 
Steps to reproduce: 
I added the LTI to my test course.
From my student account (studsf), I added a submission.
As an admin, I clicked on the student account username and it gave me a 500 server error.
I wasn't sure why that happened. 
I added another account (betasf) and this one worked as it should.
I then added a third account (mitx-tech-request) and this one also gave a 500 error. 
The two accounts that gave the error were also enrolled in the B101 test course so i thought it had to do with that, but maybe not.
Let me know if you need more info.

**Comment by alvinsiu** [comment]
Thanks!  That was really helpful - found the bug and am creating a pull request for it.
