### ISSUE TITLE
Error (400) bad request while connecting from OPEN EDX LMS

### ISSUE THREAD

**Issue by koljanos** [mitodl/sga-lti#64]
Hello, I've recently installed sga-lti on heroku.
Have not changed a thing in code, just changed `sga-lti.yml` file. I made it to look as followed
`ALLOWED_HOSTS             [".inrobot.ru", "inrobot-lti-sga.herokuapp.com"]
DATABASE_URL              postgres://bdoxlzafnqhvks:Oap19v97o-_bFfQFRBDdvk6fkq@ec2-54-243-52-211.compute-1.amazonaws.com:5432/d3vsn5f6ksv0s1
LTI_OAUTH_CREDENTIALS     {bububu: dududu}
AWS_STORAGE_BUCKET_NAME   idiotsandtrobots
AWS_ACCESS_KEY_ID         HERE IS MY KEY
AWS_SECRET_ACCESS_KEY     HERE IS MY SECRET
MEDIAFILES_LOCATION       /sga_files
SECRET_KEY                babdadam
`

And when I tail heroku logs i get following errors while trying to connect to lti server from edx
`ERROR 15 [django.security.DisallowedHost] base.py:216 - [8311f173-fea6-4af9-b32d-9bfa40cbe99a] - Invalid HTTP_HOST header: 'inrobot-lti-sga.herokuapp.com'. You may need to add 'inrobot-lti-sga.herokuapp.com' to ALLOWED_HOSTS.`

If anyone can answer my question, it would be much appreciated. Thanks in advance.

**Comment by alvinsiu** [comment]
Not sure if this is just an error in copying and pasting, but are there colons between your key/value pairs?

`ALLOWED_HOSTS: [".inrobot.ru", "inrobot-lti-sga.herokuapp.com"]`

**Comment by koljanos** [comment]
Yup, there are i left everything same as in cml file except aws credentials

**Comment by pdpinch** [comment]
Couple questions:

- Are your edX instance and your LTI instance both running over https?
- Is this inline, or in a new window? 
- What browser are you using?
- Are you able to connect to the app directly, without going over LTI?

**Comment by koljanos** [comment]
- edX instance is not an https
- it is inline
- I am using safari on macos
- when I go http://inrobot-lti-sga.herokuapp.com or https it is still error `400 bad request`

**Comment by pdpinch** [comment]
@alvinsiu I've gotten confused about how ALLOWED_HOSTS is used. Can it have more than one value?

**Comment by alvinsiu** [comment]
Yes, it can have more than one value - should be stored as a list.

[Here's the Django documentation on that!](https://docs.djangoproject.com/en/1.10/ref/settings/#allowed-hosts)

**Comment by alvinsiu** [comment]
@koljanos I haven't touched this code in a while, so I'm not sure if this matters, but if you're not running it on https, you may also need to set these fields.  Could be a Django thing.

```
SGA_LTI_SECURE_SSL_REDIRECT: False
SGA_LTI_DB_DISABLE_SSL: True
```

**Comment by koljanos** [comment]
@alvinsiu I've checked these variables they are the same as you stated them.
i forgot one thing, I've changed `settings.py` to adress heroku error containing static assets.
So I added 
`PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))`
`# Static files (CSS, JavaScript, Images)`
`# https://docs.djangoproject.com/en/1.9/howto/static-files/`
`STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')`
`STATIC_URL = '/static/'`
`# Extra places for collectstatic to find static files.`
`STATICFILES_DIRS = (`
`    os.path.join(PROJECT_ROOT, 'static'),`
` ) `

more can be found here: https://devcenter.heroku.com/articles/django-assets

**Comment by alvinsiu** [comment]
@koljanos Have you got it working yet?  Without more information, it's not really easy to debug the exact cause of your error.  If you haven't already, I would try a couple of things:

1. Restarting your app to reload the settings you've set in `sga-lti.yml`
2. Logging into your heroku instance and inspecting the settings yourself (is `ALLOWED_HOSTS` being set correctly? etc.)
3. Ensure all LTI parameters are set up correctly on your EdX instance, since sometimes this can cause misleading errors

**Comment by koljanos** [comment]
@alvinsiu okay, maybe I've messed up something.
I've created new heroku app.
I am trying to deploy my branch of sga-lti repo
I add heroku postgres add-on
and deploy my branch, WITHOUT any changes, nor sga-lti.yml file
then i get following build log:
`  $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "manage.py", line 14, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 176, in handle
           collected = self.collect()
         File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 98, in collect
           for path, storage in finder.list(self.ignore_patterns):
         File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/finders.py", line 112, in list
           for path in utils.get_files(storage, ignore_patterns):
         File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
           directories, files = storage.listdir(location)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/files/storage.py", line 299, in listdir
           for entry in os.listdir(path):
       FileNotFoundError: [Errno 2] No such file or directory: '/app/sga_lti/static'
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed`
What should I change to get my LTI running.

**Comment by alvinsiu** [comment]
@koljanos Let's continue this conversation over email for quicker responses. You can find my email on my [public profile](https://github.com/alvinsiu).

**Comment by koljanos** [comment]
Thanks for help, I will be researching more on the topic.
